[tool.poetry]
name = "akari-bot"
version = "0.1.0"
description = ""
authors = [
    "OasisAkari <oasisakari@teahou.se>",
    "Dianliang233 <dianliang@teahou.se>",
    "DoroWolf <dorowolf@tehou.se>",
    "nullcat <null@teahou.se>",
    "_LittleC_ <i@ltlec.com>",
]
license = "AGPL-3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12.0"
Pillow = "^11.0.0"
aiohttp = ">=3.9.3"
beautifulsoup4 = "^4.11.1"
psutil = "^6.0.0"
gql = "^3.4.0"
filetype = "^1.2.0"
SQLAlchemy = "^2.0.20"
APScheduler = "^3.9.1-post.0"
aiogram = "^3.4.1"
PyMySQL = "^1.0.2"
py-cord = "^2.5.0"
aiocqhttp = "^1.4.3"
tabulate = "^0.9.0"
feedparser = "^6.0.10"
ffmpy = "^0.4.0"
google-play-scraper = "^1.2.2"
py-cpuinfo = "^9.0.0"
aiofile = "^3.8.1"
loguru = "^0.7.0"
numpy = "^1.24.1"
matplotlib = "^3.6.3"
pint = "^0.24.0"
simpleeval = "^1.0.0"
pywin32 = { version = "^306", platform = "win32" }
tenacity = "^9.0.0"
openai = "^1.6.1"
cryptography = "^43.0.0"
pre-commit = "^4.0.0"
webcolors = "^24.0.0"
langchain = "^0.3.0"
wolframalpha = "^5.0.0"
duckduckgo-search = "^6.0.0"
tiktoken = "^0.8.0"
pycryptodome = "^3.18.0"
khl-py = "^0.3.16"
matrix-nio = "^0.25.0"
attrs = "^24.2.0"
uvicorn = {extras = ["standard"], version = "^0.32.0"}
pyjwt = {extras = ["crypto"], version = "^2.8.0"}
python-whois = "^0.9.0"
pandas = "^2.2.0"
future = "^1.0.0"
fastapi = "^0.115.0"
inputimeout = "^1.0.4"
prompt-toolkit = "^3.0.47"
emoji = "^2.12.1"
langconv = {git = "https://github.com/OasisAkari/langconv.py.git"}
ff3 = "^1.0.2"
orjson = "^3.10.9"
jinja2 = "^3.1.4"
mcstatus = "^11.1.1"
qq-botpy = "^1.2.1"
botpy = {git = "https://github.com/Teahouse-Studios/botpy.git"}
tomlkit = "^0.13.2"
cattrs = "^24.1.2"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
pycodestyle = "2.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 3

[tool.pyright]
reportUndefinedVariable = 'error'
