[tool.poetry]
name = "akari-bot"
version = "0.1.0"
description = ""
authors = [
    "OasisAkari <oasisakari@teahou.se>",
    "Dianliang233 <dianliang@teahou.se>",
    "DoroWolf <dorowolf@tehou.se>",
    "nullcat <null@teahou.se>",
    "_LittleC_ <i@ltlec.com>",
]
license = "AGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
Pillow = "^9.4.0"
aiohttp = "^3.8.3"
beautifulsoup4 = "^4.11.1"
psutil = "^5.9.4"
gql = "^3.4.0"
filetype = "^1.2.0"
SQLAlchemy = "^1.4.46"
APScheduler = "^3.9.1.post1"
aioconsole = "^0.6.1"
aiogram = "^2.24"
ujson = "^5.7.0"
PyMySQL = "^1.0.2"
py-cord = "^2.3.2"
aiocqhttp = "^1.4.3"
tabulate = "^0.9.0"
feedparser = "^6.0.10"
ffmpy = "^0.3.0"
google-play-scraper = "^1.2.2"
py-cpuinfo = "^9.0.0"
aiofile = "^3.8.1"
loguru = "^0.6.0"
numpy = "^1.24.1"
matplotlib = "^3.6.3"
pint = "^0.21"
simpleeval = "^0.9.12"
pywin32 = { version = "^305", platform = "win32" }
tenacity = "^8.1.0"
openai = "^0.27.2"
cryptography = "^41.0.0"
pre-commit = "^3.0.4"
webcolors = "^1.12"
langchain = "^0.0.206"
wolframalpha = "^5.0.0"
duckduckgo-search = "^3.0.0"
chromadb = "^0.3.21"
tiktoken = "^0.3.3"
pycryptodome = "^3.18.0"
langconv = "^0.2.0"
toml = "^0.10.2"
khl-py = "^0.3.16"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 3

[tool.pyright]
reportUndefinedVariable = 'error'
