# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字でなければならないです。

[bot_web]
# プラットフォーム側の設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
login_max_attempts = 5 # ログイン要求の上限回数。
enable = true # このプラットフォームを有効にするかどうか。
enable_https = false # HTTPS プロトコルのセキュリティ対策を有効にするかどうか。
heartbeat_interval = 30 # ハートビート メッセージを送信する間隔。
heartbeat_timeout = 5 # ハートビート メッセージ応答のタイムアウト。
heartbeat_attempt = 3 # ハートビート メッセージを送信する試行回数。
web_host = "127.0.0.1" # Web サービスのホスト アドレス。0.0.0.0 に設定すると、すべてのアドレスをリッスンします。
web_port = 6485 # Web サービスのポート番号。0 に設定するとサービスが無効になります。

[bot_web_secret]
# プラットフォーム側のキー設定項目です。ここに入力された値は、送信メッセージに誤って含まれた場合、ボットはそれを傍受しようとします。ただし、漏洩を防ぐよう注意してください。
allow_origins = [] # API サービスで CORS が許可されるオリジンのリスト。
jwt_secret = "<Replace me with str value>" # 組み込み API 認証のキー、署名と有効性の検証のため。
