# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字でなければならないです。

default_locale = "ja_jp" # デフォルトのセッション ロケール。
config_version = 2 # バージョン番号。機能アップデートに伴い自動的に増加されるので、通常は変更しないでください。

[config]
# 基本的な設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
debug = false # デバッグモードを有効にするかどうか。有効にすると、より多くのログ情報が出力されます。
base_superuser = ["QQ|2596322644"] # ボットの基本スーパーユーザー リスト。ここに入力された値はボットの起動時にデータベースに読み込まれます。
rickroll_msg = "<Replace me with str value>" # テキスト フィルタ リング検出に失敗したときのリックロール メッセージ。
enable_rickroll = true # テキスト フィルタの検出に失敗したときに、ユーザーをリックロールするかどうか。
report_targets = [] # レポート セッション リスト。ここに入力された値がレポートセッションとして認識されます。（例：コマンド エラーを実行すると、ボットは対応するセッションにエラー情報を送信します）
tos_warning_counts = 5 # 利用規約違反に対する警告の最大数。
issue_url = "https://github.com/Teahouse-Studios/bot/issues/new/choose" # フィードバックの URL。
enable_joke = true # ジョークを有効にするかどうか。有効にすると、サーバー時間の 4 月 1 日（エイプリルフール）に実行されます。
shuffle_rate = 0.1 # ジョークのランダム発生率。範囲は 0 から 1 です。
unloaded_modules = [] # ロードされないモジュールのリスト。このリストに一致するモジュールはロードされない。
use_font_mirror = false # ウェブページのをレンダリングするときにフォントのミラーリングを使用するかどうか。
use_secrets_random = false # secrets ライブラリに基づく乱数ジェネレータを使用するかどうか。
enable_petal = false # ペタル機能を有効にするかどうか。
enable_get_petal = false # ペタルの取得を許可するかどうか。
petal_gained_limit = 0 # 1日に獲得できるペタルの最大数。
petal_lost_limit = 0 # 1日に失われたペタルの最大数。
petal_sign_limit = 5 # 1日にサインインすることで獲得できるペタルの最大数。
petal_sign_rate = 0.5 # サインインすることでペタルを獲得できる確率は 0 から 1 の範囲で、獲得できるペタルの数は指数関数的に減少します。
allow_request_private_ip = false # ボットがローカル プライベート IP アドレスをリクエストすることを許可するかどうか。（情報漏洩を防ぐため）
ignored_sender = ["QQ|2854196310"] # 無視されるユーザーのリスト。このリストにマッチしたユーザーは無視されます。
enable_tos = true # 組み込みの ToS（利用規約）チェック ルールを有効にするかどうか。
enable_analytics = false # 組み込みの統計機能を有効にするかどうか。
enable_module_invalid_prompt = false # モジュールが存在しない場合にプロンプ​​ト メッセージを有効にするかどうか。
bug_report_url = "https://s.wd-ljt.com/botreportbug" # エラーを報告するための URL。
tos_temp_ban_time = 300 # 利用規約違反時の一時的な禁止時間。
no_confirm = false # 送信者がメッセージを確認せずにコマンドを実行するかどうか。
timezone_offset = "+8" # ボットのデフォルトのタイムゾーン オフセット。
confirm_command = ["是", "对", "對", "yes", "Yes", "YES", "y", "Y"] # コマンド確認用のキーワード。ここに入力された値はコマンド確認用の単語として認識されます。
command_prefix = ["~", "～"] # コマンドのプレフィックス。ここに入力された値はコマンドのプレフィックスとして認識されます。
enable_dirty_check = false # テキスト フィルタ リング検出を有効にするかどうか。Alibaba Cloud コンテンツ セキュリティ サービスの AccessKey ID と AccessKey Secret を設定する必要があります。
enable_urlmanager = false # URL スプリングボードの URLManager を有効にするかどうか。（URL が公式リンクではないことを宣言するなど）
enable_eval = false # eval モジュールを有効にするかどうか。
help_url = "https://bot.teahouse.team" # ドキュメントの URL。
donate_url = "http://afdian.com/a/teahouse" # 寄付の URL。
help_page_url = "https://bot.teahouse.team/wiki/${module}" # モジュールのヘルプ情報の URL。
allow_reload_base = false # 基本モジュールの再読み込みを許可するかどうか。
enable_commit_url = true # バージョン情報を表示する時にコミット URL を表示するかどうか。
locale_url = "https://www.crowdin.com/project/akari-bot" # 翻訳プロジェクトの URL。
slower_schedule = false # 低速のスケジュールタスクスケジューラを有効にするかどうか。（リクエストの負荷を軽減するため）


[secret]
# キーの設定項目です。ここに入力された値は、送信メッセージに誤って含まれた場合、ボットはそれを傍受しようとします。ただし、漏洩を防ぐよう注意してください。
check_access_key_id = "<Replace me with str value>" # Alibaba Cloud コンテンツ セキュリティ サービスの AccessKey ID。
check_access_key_secret = "<Replace me with str value>" # Alibaba Cloud コンテンツ セキュリティ サービスの AccessKey Secret。
ff3_key = "<Replace me with str value>" # 用于加密敏感信息的密钥。（使用 ff3 算法进行加密，部分场景可能会使用到）
ff3_tweak = "<Replace me with str value>" # 用于加密敏感信息的密钥偏移量。
proxy = "<Replace me with str value>" # プロキシ サービスのアドレス。
db_path = "sqlite://database/save.db" # データベース接続文字列。Tortoise ORM でサポートされているデータベース接続文字列形式を使用してください。
