# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字でなければならないです。

[module_maimai_secret]
# モジュールのキー設定項目です。ここに入力された値は、送信メッセージに誤って含まれた場合、ボットはそれを傍受しようとします。ただし、漏洩を防ぐよう注意してください。
diving_fish_developer_token = "<Replace me with str value>" # Diving Fish 查分器的开发者令牌。（用于 maimai 模块）
lxns_developer_token = "<Replace me with str value>" # 落雪咖啡屋查分器的开发者令牌。（用于 maimai 模块）
