# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。請不要在此處使用 Python 語法。
# 例如：TOML 中的布林值必須是小寫。

[bot_web]
# 平台端的設定部分，此處填寫的值可在訊息中以明文顯示。請不要在此部分填寫敏感資訊。
enable_https = false # 是否啟用 HTTPS 協議安全措施。
web_host = "127.0.0.1" # Web 服務的主機位址，設為 0.0.0.0 則監聽所有位址。
web_port = 8081 # Web 服務的連接埠號，設為 0 則停用服務。
login_max_attempts = 5 # 登入請求最大次數限制。
enable = true # 是否啟用此平台。

[bot_web_secret]
# 平台端的金鑰設定部分，此處的值若意外出現在傳送的訊息中，機器人會嘗試攔截。但請務必提防洩漏。
allow_origins = [] # API 服務允许 CORS 的來源列表。
jwt_secret = "<Replace me with str value>" # 內建 API 的身份認證金鑰，用於簽署和驗證有效性。
