# https://toml.io/en/v1.0.0
# NOTE: TOML is not like Python. Do not use Python syntax here.
# EXAMPLE: Boolean values in TOML must be lowercase.

[bot_aiogram]
# The basic config section of the platform. The value ​​filled in here can be displayed in the message. Please do not fill in sensitive information in this section.
enable = false # Whether to enable this platform.
telegram_api_url = "<Replace me with str value>" # Telegram custom API URL。

[bot_aiogram_secret]
# The secret config section of the platform. The bot will try to intercept if the value here accidentally appears in the message sent, but be careful to prevent leakage.
telegram_token = "<Replace me with str value>" # Telegram bot token.
